# Generated by Django 2.2.4 on 2019-11-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('datee', models.DateField()),
            ],
        ),
    ]
